In [27]:
#create a blank matrix
m = matrix(, nrow = 10, ncol = 5)

In [28]:
m

[,1] [,2] [,3] [,4] [,5]
 [1,] NA   NA   NA   NA   NA  
 [2,] NA   NA   NA   NA   NA  
 [3,] NA   NA   NA   NA   NA  
 [4,] NA   NA   NA   NA   NA  
 [5,] NA   NA   NA   NA   NA  
 [6,] NA   NA   NA   NA   NA  
 [7,] NA   NA   NA   NA   NA  
 [8,] NA   NA   NA   NA   NA  
 [9,] NA   NA   NA   NA   NA  
[10,] NA   NA   NA   NA   NA

In [29]:
# create a matrix taking a given vector of numbers as input
input_vector <- c(1, 2, 3, 4, 5, 6, 7, 8, 9)

# Create a matrix from the input vector
result_matrix <- matrix(input_vector, nrow = 3, ncol = 3, byrow = TRUE)

result_matrix

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [30]:
#defines column and row names
row_names <- c("Row1", "Row2", "Row3")
col_names <- c("Col1", "Col2", "Col3")

In [31]:
rownames(result_matrix) <- row_names
colnames(result_matrix) <- col_names

In [32]:
result_matrix

Col1 Col2 Col3
Row1 1    2    3   
Row2 4    5    6   
Row3 7    8    9

In [33]:
## Access and print the element located at the 2nd row and 3rd column of the matrix
x = result_matrix[2,3]
x

[1] 6

In [37]:
#Write a R program to concatenate two given matrices of same column but different rows.

# Create the first matrix
matrix1 <- matrix(1:12, nrow = 4, ncol = 3)

# Create the second matrix
matrix2 <- matrix(13:24, nrow = 4, ncol = 3)

# Concatenate the two matrices
result <- rbind(matrix1, matrix2)

# Print the result
print(result)

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12
[5,]   13   17   21
[6,]   14   18   22
[7,]   15   19   23
[8,]   16   20   24
