Write a R program to convert a given matrix to a 1 dimensional array.

In [3]:
mat =  matrix (1:10, nrow = 2, ncol = 2)
mat


[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [4]:
vector_1 <- as.vector (mat)
vector_1

[1] 1 2 3 4

Write a R program to create an array of two 3x3 matrices each with 3 rows and 3 columns from two given two vectors.

In [8]:
vector_1 <- c(1,2,3,4,5,6,7)
vector_2 <- c(120,239,377,479,544,699,723,886,955,100)

matrix_values =  array(c(vector_1,vector_2), dim = c(3,3,2))

print(matrix_values)

, , 1

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5  120
[3,]    3    6  239

, , 2

     [,1] [,2] [,3]
[1,]  377  699  955
[2,]  479  723  100
[3,]  544  886    1



Write a R program to create an 3 dimensional array of 24 elements using the dim() function.

In [17]:
elements <- 1:24
dim(elements) <- c(4, 3, 2) 

print(elements)

, , 1

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

, , 2

     [,1] [,2] [,3]
[1,]   13   17   21
[2,]   14   18   22
[3,]   15   19   23
[4,]   16   20   24



Write a R program to create an array of two 3x3 matrices each with 3 rows and 3 columns from two given two vectors. Print the second row of the second matrix of the array and the element in the 3rd row and 3rd column of the 1st matrix.

In [19]:
# Given two vectors
vector1 <- c(1, 2, 3, 4, 5, 6, 7, 8, 9)
vector2 <- c(10, 11, 12, 13, 14, 15, 16, 17, 18)

In [20]:

# Create a 3x3 matrix for each vector
matrix1 <- matrix(vector1, nrow = 3, ncol = 3)
matrix2 <- matrix(vector2, nrow = 3, ncol = 3)

In [24]:
array_matrices <- array(c(matrix1, matrix2), dim = c(3, 3, 2))
print(array_matrices)

, , 1

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

, , 2

     [,1] [,2] [,3]
[1,]   10   13   16
[2,]   11   14   17
[3,]   12   15   18



In [ ]:
# second row of the second matrix
print(array_matrices[2, , 2])

[1] 11 14 17


In [ ]:
# 3rd row and 3rd column of the 1st matrix
print(array_matrices[3, , 1])

[1] 3 6 9


Write a R program to create a two-dimensional 5x3 array of sequence of even integers greater than 50.

In [33]:
even_integers <- seq(52, by = 2, length.out = 15)

array_even <- matrix(even_integers, nrow = 5, ncol = 3)

cat("5x3 array of even integers greater than 50:\n")
print(array_even)

5x3 array of even integers greater than 50:
     [,1] [,2] [,3]
[1,]   52   62   72
[2,]   54   64   74
[3,]   56   66   76
[4,]   58   68   78
[5,]   60   70   80
